server:
  port: 8080
spring:
  jpa:
    show-sql: true
#http://localhost:8080/h2-console/
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        loggerLevel: basic
logging:
  level:
    root: debug

weather:
  id:
  url: "api.openweathermap.org/data/2.5/forecast"
  absoluteFilePath:
  fixedDelayInMilli: 30000
