server:
  port: 4200
spring:
  jpa:
    show-sql: true
#http://localhost:4200/h2-console/
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
#        loggerLevel: basic
logging:
  level:
    root: debug

weather:
  id: "3911bd7cee3868d7c68a6036b715280e"
  url: "api.openweathermap.org/data/2.5/forecast"
  absoluteFilePath: "C:\\Pessoal\\Projects\\weatherAPI\\src\\test\\resources\\json\\locationsToMonitor.json"
