server:
  port: 4200
spring:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
